export const kvpyData = [
    {
      id: 1,
      name: 2017,
      title: "Physics1",
      file: "",
    },
    {
      id: 2,
      name: 2017,
      title: "Chemistry1",
      file: "",
    },
    {
      id: 3,
      name: 2017,
      title: "Maths1",
      file: "",
    },
    {
      id: 4,
      name: 2017,
      title: "Physics2",
      file: "",
    },
    {
      id: 5,
      name: 2017,
      title: "Chemistry2",
      file: "",
    },
    {
      id: 6,
      name: 2017,
      title: "Maths2",
      file: "",
    },
    {
      id: 7,
      name: 2018,
      title: "Physics1",
      file: "",
    },
    {
      id: 8,
      name: 2018,
      title: "Chemistry1",
      file: "",
    },
    {
      id: 9,
      name: 2018,
      title: "Maths1",
      file: "",
    },
    {
      id: 10,
      name: 2018,
      title: "Physics2",
      file: "",
    },
    {
      id: 11,
      name: 2018,
      title: "Chemistry2",
      file: "",
    },
    {
      id: 12,
      name: 2018,
      title: "Maths2",
      file: "",
    },
    {
      id: 13,
      name: 2019,
      title: "Physics1",
      file: "",
    },
    {
      id: 14,
      name: 2019,
      title: "Chemistry1",
      file: "",
    },
    {
      id: 15,
      name: 2019,
      title: "Maths1",
      file: "",
    },
    {
      id: 16,
      name: 2019,
      title: "Physics2",
      file: "",
    },
    {
      id: 17,
      name: 2019,
      title: "Chemistry2",
      file: "",
    },
    {
      id: 18,
      name: 2019,
      title: "Maths2",
      file: "",
    },
    {
      id: 19,
      name: 2020,
      title: "Physics1",
      file: "",
    },
    {
      id: 20,
      name: 2020,
      title: "Chemistry1",
      file: "",
    },
    {
      id: 21,
      name: 2020,
      title: "Maths1",
      file: "",
    },
    {
      id: 22,
      name: 2020,
      title: "Physics2",
      file: "",
    },
    {
      id: 23,
      name: 2020,
      title: "Chemistry2",
      file: "",
    },
    {
      id: 24,
      name: 2020,
      title: "Maths2",
      file: "",
    },
    {
      id: 25,
      name: 2021,
      title: "Physics1",
      file: "",
    },
    {
      id: 26,
      name: 2021,
      title: "Chemistry1",
      file: "",
    },
    {
      id: 27,
      name: 2021,
      title: "Maths1",
      file: "",
    },
    {
      id: 28,
      name: 2021,
      title: "Physics2",
      file: "",
    },
    {
      id: 29,
      name: 2021,
      title: "Chemistry2",
      file: "",
    },
    {
      id: 30,
      name: 2021,
      title: "Maths2",
      file: "",
    },
    {
      id: 31,
      name: 2022,
      title: "Physics1",
      file: "",
    },
    {
      id: 32,
      name: 2022,
      title: "Chemistry1",
      file: "",
    },
    {
      id: 33,
      name: 2022,
      title: "Maths1",
      file: "",
    },
    {
      id: 34,
      name: 2022,
      title: "Physics2",
      file: "",
    },
    {
      id: 35,
      name: 2022,
      title: "Chemistry2",
      file: "",
    },
    {
      id: 36,
      name: 2022,
      title: "Maths2",
      file: "",
    },
    {
      id: 37,
      name: 2023,
      title: "Physics1",
      file: "",
    },
    {
      id: 38,
      name: 2023,
      title: "Chemistry1",
      file: "",
    },
    {
      id: 39,
      name: 2023,
      title: "Maths1",
      file: "",
    },
    {
      id: 40,
      name: 2023,
      title: "Physics2",
      file: "",
    },
    {
      id: 41,
      name: 2023,
      title: "Chemistry2",
      file: "",
    },
    {
      id: 42,
      name: 2023,
      title: "Maths2",
      file: "",
    },
  ];
  