export const ncertData = [
    {
      id: 1,
      name: 'class6',
      title: "Maths",
      file: "",
    },
    {
      id: 2,
      name: 'class6',
      title: "Science",
      file: "",
    },
    {
      id: 3,
      name: 'class7',
      title: "Maths",
      file: "",
    },
    {
      id: 4,
      name: 'class7',
      title: "Science",
      file: "",
    },
    {
      id: 5,
      name: 'class8',
      title: "Maths",
      file: "",
    },
    {
      id: 6,
      name: 'class8',
      title: "Science",
      file: "",
    },
    {
      id: 7,
      name: 'class9',
      title: "Physics",
      file: "",
    },
    {
      id: 8,
      name: 'class9',
      title: "Chemistry",
      file: "",
    },
    {
      id: 9,
      name: 'class9',
      title: "Maths",
      file: "",
    },
    {
      id: 10,
      name: 'class10',
      title: "Physics",
      file: "",
    },
    {
      id: 11,
      name: 'class10',
      title: "Chemistry",
      file: "",
    },
    {
      id: 12,
      name: 'class10',
      title: "Maths",
      file: "",
    },
    {
      id: 13,
      name: 'class11',
      title: "Physics1",
      file: "",
    },
    {
      id: 14,
      name: 'class11',
      title: "Chemistry1",
      file: "",
    },
    {
      id: 15,
      name: 'class11',
      title: "Maths1",
      file: "",
    },
    {
      id: 16,
      name: 'class11',
      title: "Physics2",
      file: "",
    },
    {
      id: 17,
      name: 'class11',
      title: "Chemistry2",
      file: "",
    },
    {
      id: 18,
      name: 'class11',
      title: "Maths2",
      file: "",
    },
    {
      id: 19,
      name: 'class12',
      title: "Physics1",
      file: "",
    },
    {
      id: 20,
      name: 'class12',
      title: "Chemistry1",
      file: "",
    },
    {
      id: 21,
      name: 'class12',
      title: "Maths1",
      file: "",
    },
    {
      id: 22,
      name: 'class12',
      title: "Physics2",
      file: "",
    },
    {
      id: 23,
      name: 'class12',
      title: "Chemistry2",
      file: "",
    },
    {
      id: 24,
      name: 'class12',
      title: "Maths2",
      file: "",
    },
  ];
  