export const neetData = [
    {
      id: 1,
      name: 2017,
      title: "Physics",
      file: "",
    },
    {
      id: 2,
      name: 2017,
      title: "Chemistry",
      file: "",
    },
    {
      id: 3,
      name: 2017,
      title: "Biology",
      file: "",
    },
    {
      id: 4,
      name: 2018,
      title: "Physics",
      file: "",
    },
    {
      id: 5,
      name: 2018,
      title: "Chemistry",
      file: "",
    },
    {
      id: 6,
      name: 2018,
      title: "Biology",
      file: "",
    },
    {
      id: 7,
      name: 2019,
      title: "Physics",
      file: "",
    },
    {
      id: 8,
      name: 2019,
      title: "Chemistry",
      file: "",
    },
    {
      id: 9,
      name: 2019,
      title: "Biology",
      file: "",
    },
    {
      id: 10,
      name: 2020,
      title: "Physics",
      file: "",
    },
    {
      id: 11,
      name: 2020,
      title: "Chemistry",
      file: "",
    },
    {
      id: 12,
      name: 2020,
      title: "Biology",
      file: "",
    },
    {
      id: 13,
      name: 2021,
      title: "Physics",
      file: "",
    },
    {
      id: 14,
      name: 2021,
      title: "Chemistry",
      file: "",
    },
    {
      id: 15,
      name: 2021,
      title: "Biology",
      file: "",
    },
    {
      id: 16,
      name: 2022,
      title: "Physics",
      file: "",
    },
    {
      id: 17,
      name: 2022,
      title: "Chemistry",
      file: "",
    },
    {
      id: 18,
      name: 2022,
      title: "Biology",
      file: "",
    },
    {
      id: 19,
      name: 2023,
      title: "Physics",
      file: "",
    },
    {
      id: 20,
      name: 2023,
      title: "Chemistry",
      file: "",
    },
    {
      id: 21,
      name: 2023,
      title: "Biology",
      file: "",
    },
  ];
  